# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: partyrentingplatform
services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile-Back
    ports:
      - 127.0.0.1:5000:8080
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
